//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AMU
    {
        public int ID { get; set; }
        [Required]
        [DisplayName("Apartman Adı")]
        public Nullable<int> ADID { get; set; }
        [Required]
        [DisplayName("Yönetici KullanıcıAdı")]
        public Nullable<int> UID { get; set; }

        public virtual ApartmantDetails ApartmantDetails { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
