//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMU
    {
        public int ID { get; set; }
        public Nullable<int> ADID { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual ApartmantDetails ApartmantDetails { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
