//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ResidentAccountDetailView
    {
        public string NAMESURNAME { get; set; }
        public string C_ADDRESS { get; set; }
        public string GSM { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string TOWNS { get; set; }
        public string DISTRICT { get; set; }
        public string NAME { get; set; }
        public string BLOCNAME { get; set; }
        public string KATNO { get; set; }
        public Nullable<int> DAIRENO { get; set; }
        public Nullable<decimal> BAKİYE { get; set; }
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public int ResidentID { get; set; }
    }
}
