//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserYetkiView
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string AD_SOYAD { get; set; }
        public string email { get; set; }
        public string GENDER { get; set; }
        public string TELEPHONE { get; set; }
        public string YETKI { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string TOWNS { get; set; }
        public string DISTRICT { get; set; }
        public string C_ADDRESS { get; set; }
    }
}
