//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class DAIRELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAIRELER()
        {
            this.RESIDENT = new HashSet<RESIDENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ABID { get; set; }
        public Nullable<int> KATID { get; set; }
        public Nullable<int> DAIRENO { get; set; }
        public Nullable<int> ADID { get; set; }
    
        public virtual ApartmantBlocs ApartmantBlocs { get; set; }

        public IEnumerable<SelectListItem> blocid { get; set; }

        public virtual KATLAR KATLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESIDENT> RESIDENT { get; set; }
        public virtual ApartmantDetails ApartmantDetails { get; set; }
    }
}
