//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESIDENT()
        {
            this.ResidentAccount = new HashSet<ResidentAccount>();
            this.ResidentRevenus = new HashSet<ResidentRevenus>();
            this.ResidentExpense = new HashSet<ResidentExpense>();
        }
    
        public int ID { get; set; }
        public string NAMESURNAME { get; set; }
        public string C_ADDRESS { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public Nullable<int> CITY { get; set; }
        public Nullable<int> TOWNS { get; set; }
        public Nullable<int> DISTRICTS { get; set; }
        public Nullable<int> ApartmanID { get; set; }
        public Nullable<int> ApartmanBlocs { get; set; }
        public Nullable<int> KatID { get; set; }
        public int DAIREID { get; set; }
        public string GSM { get; set; }
    
        public virtual ApartmantBlocs ApartmantBlocs { get; set; }
        public virtual ApartmantDetails ApartmantDetails { get; set; }
        public virtual CITY CITY1 { get; set; }
        public virtual COUNTRY COUNTRY1 { get; set; }
        public virtual DAIRELER DAIRELER { get; set; }
        public virtual DISTRICTS DISTRICTS1 { get; set; }
        public virtual KATLAR KATLAR { get; set; }
        public virtual TOWNS TOWNS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentAccount> ResidentAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentRevenus> ResidentRevenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResidentExpense> ResidentExpense { get; set; }
    }
}
