//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.AMU = new HashSet<AMU>();
            this.Images = new HashSet<Images>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string C_PASSWORD { get; set; }
        public string C_NAME { get; set; }
        public string C_SURNAME { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public Nullable<int> CITY { get; set; }
        public Nullable<int> TOWNS { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public string C_ADDRESS { get; set; }
        public string GENDER { get; set; }
        public string email { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<int> YETKIID { get; set; }
        public string img { get; set; }
        public IEnumerable<SelectListItem> ct { get; set; }
        public IEnumerable<SelectListItem> c { get; set; }
        public IEnumerable<SelectListItem> t { get; set; }
        public IEnumerable<SelectListItem> d { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMU> AMU { get; set; }
        public virtual CITY CITY1 { get; set; }
        public virtual COUNTRY COUNTRY1 { get; set; }
        public virtual DISTRICTS DISTRICTS { get; set; }
        public virtual TOWNS TOWNS1 { get; set; }
        public virtual YETKILER YETKILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
